# Generated by Django 4.1.5 on 2023-02-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_user_face_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='face_image',
            field=models.ImageField(upload_to='face_images/'),
        ),
    ]
